/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface MyComponent {}
  interface TokboxLoader {}
}

declare global {


  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLTokboxLoaderElement extends Components.TokboxLoader, HTMLStencilElement {}
  var HTMLTokboxLoaderElement: {
    prototype: HTMLTokboxLoaderElement;
    new (): HTMLTokboxLoaderElement;
  };
  interface HTMLElementTagNameMap {
    'my-component': HTMLMyComponentElement;
    'tokbox-loader': HTMLTokboxLoaderElement;
  }
}

declare namespace LocalJSX {
  interface MyComponent extends JSXBase.HTMLAttributes<HTMLMyComponentElement> {}
  interface TokboxLoader extends JSXBase.HTMLAttributes<HTMLTokboxLoaderElement> {}

  interface IntrinsicElements {
    'my-component': MyComponent;
    'tokbox-loader': TokboxLoader;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


